CREATE TABLE `order` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_sn` char(20) NOT NULL COMMENT '订单编号',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户id',
  `order_status` tinyint(4) unsigned NOT NULL DEFAULT '0' COMMENT '订单状态 0待确认 1已确认 2已取消',
  `shipping_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '发货状态 0未发货 1已发货 2已签收',
  `pay_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '支付状态 0未支付 1已支付 2已支付部分款',
  `consignee` varchar(60) NOT NULL COMMENT '收货人',
  `city` int(10) unsigned NOT NULL COMMENT '城市',
  `address` varchar(255) NOT NULL COMMENT '地址',
  `zipcode` char(6) NOT NULL DEFAULT '000000' COMMENT '邮政编码',
  `mobile` varchar(60) NOT NULL COMMENT '手机',
  `email` varchar(255) NOT NULL DEFAULT '' COMMENT '邮件',
  `shipping_code` varchar(32) NOT NULL DEFAULT '' COMMENT '物流编号',
  `shipping_name` varchar(120) NOT NULL DEFAULT '' COMMENT '物流名称',
  `pay_code` varchar(32) NOT NULL DEFAULT '' COMMENT '支付编号',
  `pay_name` varchar(120) NOT NULL DEFAULT '' COMMENT '支付方式名称',
  `invoice_title` varchar(256) NOT NULL DEFAULT '' COMMENT '发票抬头',
  `goods_price` decimal(10,2) unsigned NOT NULL COMMENT '商品总价',
  `shipping_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '邮费',
  `user_money` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '使用余额',
  `integral` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '使用积分',
  `integral_money` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '使用积分抵多少钱',
  `order_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '应付款金额',
  `total_amount` decimal(10,2) unsigned NOT NULL COMMENT '订单总价',
  `add_time` datetime NOT NULL COMMENT '下单时间',
  `confirm_time` datetime DEFAULT NULL COMMENT '收货确认时间',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `user_note` varchar(255) NOT NULL DEFAULT '' COMMENT '用户备注',
  `admin_note` varchar(255) NOT NULL DEFAULT '' COMMENT '管理员备注',
  PRIMARY KEY (`id`),
  KEY `order_sn` (`order_sn`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';